# Generated by Django 3.2.16 on 2022-12-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestEvaluation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EvaluateRequest',
        ),
    ]
