# Generated by Django 3.2.16 on 2022-12-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestEvaluation', '0003_evaluaterequest_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaterequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Evaluation_Pics'),
        ),
    ]
